// <auto-generated />
using System;
using AutoService.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoService.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AutoService.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            ClientId = 1,
                            LicensePlate = "А001АА92",
                            Model = "Camry",
                            VIN = "JT2BF22K1W0069329",
                            Year = 2018
                        },
                        new
                        {
                            Id = 2,
                            Brand = "BMW",
                            ClientId = 2,
                            LicensePlate = "В002ВВ92",
                            Model = "320i",
                            VIN = "WBA8E5G5XHNU12345",
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Lada",
                            ClientId = 3,
                            LicensePlate = "Е003ЕЕ92",
                            Model = "Vesta",
                            VIN = "XTA21190051234567",
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Hyundai",
                            ClientId = 4,
                            LicensePlate = "К004КК92",
                            Model = "Solaris",
                            VIN = "Z94CB41BAER123456",
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Kia",
                            ClientId = 5,
                            LicensePlate = "М005ММ92",
                            Model = "Rio",
                            VIN = "KNAE251ABHA123456",
                            Year = 2022
                        });
                });

            modelBuilder.Entity("AutoService.Data.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ivanov@mail.ru",
                            FirstName = "Алексей",
                            LastName = "Иванов",
                            Phone = "+79001234567"
                        },
                        new
                        {
                            Id = 2,
                            Email = "petrov@mail.ru",
                            FirstName = "Дмитрий",
                            LastName = "Петров",
                            Phone = "+79012345678"
                        },
                        new
                        {
                            Id = 3,
                            Email = "sidorov@mail.ru",
                            FirstName = "Игорь",
                            LastName = "Сидоров",
                            Phone = "+79023456789"
                        },
                        new
                        {
                            Id = 4,
                            Email = "kozlova@mail.ru",
                            FirstName = "Мария",
                            LastName = "Козлова",
                            Phone = "+79034567890"
                        },
                        new
                        {
                            Id = 5,
                            Email = "novikov@mail.ru",
                            FirstName = "Андрей",
                            LastName = "Новиков",
                            Phone = "+79045678901"
                        });
                });

            modelBuilder.Entity("AutoService.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MasterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PartsCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("WorkCost")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarId = 1,
                            MasterName = "Коваль А.В.",
                            OrderDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartsCost = 2800m,
                            Status = "Выдан",
                            TotalCost = 6300m,
                            WorkCost = 3500m,
                            WorkDescription = "ТО-60000"
                        },
                        new
                        {
                            Id = 2,
                            CarId = 2,
                            MasterName = "Мороз В.С.",
                            OrderDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartsCost = 3200m,
                            Status = "Готов",
                            TotalCost = 4700m,
                            WorkCost = 1500m,
                            WorkDescription = "Замена тормозных колодок"
                        },
                        new
                        {
                            Id = 3,
                            CarId = 3,
                            MasterName = "Коваль А.В.",
                            OrderDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartsCost = 1200m,
                            Status = "В работе",
                            TotalCost = 2000m,
                            WorkCost = 800m,
                            WorkDescription = "Замена масла, фильтров"
                        },
                        new
                        {
                            Id = 4,
                            CarId = 4,
                            MasterName = "Семёнов И.П.",
                            OrderDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartsCost = 0m,
                            Status = "Принят",
                            TotalCost = 2000m,
                            WorkCost = 2000m,
                            WorkDescription = "Диагностика двигателя"
                        },
                        new
                        {
                            Id = 5,
                            CarId = 5,
                            MasterName = "Мороз В.С.",
                            OrderDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PartsCost = 8000m,
                            Status = "Принят",
                            TotalCost = 23000m,
                            WorkCost = 15000m,
                            WorkDescription = "Кузовной ремонт"
                        });
                });

            modelBuilder.Entity("AutoService.Data.Models.Car", b =>
                {
                    b.HasOne("AutoService.Data.Models.Client", "Client")
                        .WithMany("Cars")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AutoService.Data.Models.Order", b =>
                {
                    b.HasOne("AutoService.Data.Models.Car", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("AutoService.Data.Models.Car", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AutoService.Data.Models.Client", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
